### ISSUE TITLE
a lote of bug but thanks for that great work

### ISSUE THREAD

**Issue by bozoweed** [Arkhist/Hack-On-Net#109]
hi , so i have compiled the source of client server etc and i have seen some bug who should be report
so first in visual studio 2015 the reff for system.runtime & system.componentmodel is not found 
we can't compile the server source like we have download it whe muste fix all variable who is made with {get, set} you have write
` public int OwnerId { get => ownerId; set { ownerId = value; Dirty = true; } }
but we must rewrite that to this 
` public int OwnerId { get { return ownerId;} set { ownerId = value; Dirty = true; } }`

same for this 
                 `   if (DatabaseLink.TryLogin(client, tempUsername, tempPass, out  Int homeId))`
this not work because the out Int HomeId can't be used like this the visual studio think Int is the var but it's the type so a type can't be used like var so rewite this like this
```
int homeId; 
                    if (DatabaseLink.TryLogin(client, tempUsername, tempPass, out  homeId))
```

after that the build work fine but in game i can't use command login allways return bad user login or pass

**Comment by z-rtex** [comment]
As @Windows10CE Said.
